import { BsFiletypeCsv, BsFiletypeJson, BsFiletypePdf } from 'react-icons/bs';
import { FcGoogle } from 'react-icons/fc';
import { HiOutlineDocumentReport } from 'react-icons/hi';
import {
  LuArchive,
  LuArrowDown,
  LuArrowDownAZ,
  LuArrowLeft,
  LuArrowRight,
  LuArrowUp,
  LuArrowUpZA,
  LuBadgeAlert,
  LuBadgeCheck,
  LuBell,
  LuBookOpen,
  LuBuilding,
  LuCalendar,
  LuCalendarCheck,
  LuChartColumn,
  LuChartLine,
  LuCheck,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuChevronsLeft,
  LuChevronsRight,
  LuChevronsUpDown,
  LuChevronUp,
  LuCircleHelp,
  LuCircleUser,
  LuCode,
  LuDollarSign,
  LuDownload,
  LuEllipsis,
  LuEllipsisVertical,
  LuFile,
  LuFileJson,
  LuFileSpreadsheet,
  LuFilter,
  LuGraduationCap,
  LuGrip,
  LuHistory,
  LuHouse,
  LuInfinity,
  LuInfo,
  LuLayoutGrid,
  LuLink,
  LuLogOut,
  LuMail,
  LuMaximize2,
  LuMenu,
  LuMessageCircle,
  LuMinus,
  LuMoon,
  LuNewspaper,
  LuPartyPopper,
  LuPause,
  LuPencil,
  LuPlay,
  LuPlus,
  LuPrinter,
  LuRedo,
  LuRefreshCcw,
  LuSave,
  LuSettings,
  LuShield,
  LuSun,
  LuTable,
  LuTarget,
  LuTimer,
  LuTimerReset,
  LuTrash2,
  LuTrendingUp,
  LuUnlink,
  LuUpload,
  LuUsers,
  LuWallet,
  LuX,
} from 'react-icons/lu';
import { RiParentLine } from 'react-icons/ri';

export enum Icons {
  About = 'About',
  Account = 'Account',
  Active = 'Active',
  Alert = 'Alert',
  Archived = 'Archived',
  ArrowDown = 'ArrowDown',
  ArrowLeft = 'ArrowLeft',
  ArrowRight = 'ArrowRight',
  ArrowUp = 'ArrowUp',
  BadgeCheck = 'BadgeCheck',
  Billing = 'Billing',
  Calendar = 'Calendar',
  Caregiver = 'Caregiver',
  Check = 'Check',
  ChevronDown = 'ChevronDown',
  ChevronLeft = 'ChevronLeft',
  ChevronRight = 'ChevronRight',
  ChevronsLeft = 'ChevronsLeft',
  ChevronsRight = 'ChevronsRight',
  ChevronsUpDown = 'ChevronsUpDown',
  ChevronUp = 'ChevronUp',
  Code = 'Code',
  Contact = 'Contact',
  CSV = 'CSV',
  CSVSimple = 'CSVSimple',
  Dark = 'Dark',
  Data = 'Data',
  Delete = 'Delete',
  DollarSign = 'DollarSign',
  Download = 'Download',
  Edit = 'Edit',
  Ellipsis = 'Ellipsis',
  EllipsisVertical = 'EllipsisVertical',
  Email = 'Email',
  Export = 'Export',
  Family = 'Family',
  FAQ = 'FAQ',
  File = 'File',
  Filter = 'Filter',
  Google = 'Google',
  Graduated = 'Graduated',
  Grid = 'Grid',
  Grip = 'Grip',
  Guides = 'Guides',
  Help = 'Help',
  History = 'History',
  Home = 'Home',
  Import = 'Import',
  Infinity = 'Infinity',
  Info = 'Info',
  JSON = 'JSON',
  JSONSimple = 'JSONSimple',
  Light = 'Light',
  Link = 'Link',
  List = 'List',
  Logout = 'Logout',
  Maximize = 'Maximize',
  Minus = 'Minus',
  News = 'News',
  Notification = 'Notification',
  Organization = 'Organization',
  Party = 'Party',
  Pause = 'Pause',
  PDF = 'PDF',
  PDFSimple = 'PDFSimple',
  Play = 'Play',
  Plus = 'Plus',
  Print = 'Print',
  QuestionMark = 'QuestionMark',
  Redo = 'Redo',
  Refresh = 'Refresh',
  Report = 'Report',
  Save = 'Save',
  Session = 'Session',
  Settings = 'Settings',
  Shield = 'Shield',
  SortAlphabetical = 'SortAlphabetical',
  SortAlphabeticalReverse = 'SortAlphabeticalReverse',
  Table = 'Table',
  Target = 'Target',
  Timer = 'Timer',
  TimerReset = 'TimerReset',
  TrendingUp = 'TrendingUp',
  Unlink = 'Unlink',
  Upload = 'Upload',
  X = 'X',
}

export const ICONS = {
  [Icons.About]: LuInfo,
  [Icons.Account]: LuCircleUser,
  [Icons.Active]: LuCheck,
  [Icons.Alert]: LuBadgeAlert,
  [Icons.Archived]: LuArchive,
  [Icons.ArrowDown]: LuArrowDown,
  [Icons.ArrowLeft]: LuArrowLeft,
  [Icons.ArrowRight]: LuArrowRight,
  [Icons.ArrowUp]: LuArrowUp,
  [Icons.BadgeCheck]: LuBadgeCheck,
  [Icons.Billing]: LuWallet,
  [Icons.Calendar]: LuCalendar,
  [Icons.Caregiver]: RiParentLine,
  [Icons.Check]: LuCheck,
  [Icons.ChevronDown]: LuChevronDown,
  [Icons.ChevronLeft]: LuChevronLeft,
  [Icons.ChevronRight]: LuChevronRight,
  [Icons.ChevronsLeft]: LuChevronsLeft,
  [Icons.ChevronsRight]: LuChevronsRight,
  [Icons.ChevronsUpDown]: LuChevronsUpDown,
  [Icons.ChevronUp]: LuChevronUp,
  [Icons.Code]: LuCode,
  [Icons.CSV]: BsFiletypeCsv,
  [Icons.CSVSimple]: LuFileSpreadsheet,
  [Icons.Dark]: LuMoon,
  [Icons.Data]: LuChartLine,
  [Icons.Delete]: LuTrash2,
  [Icons.DollarSign]: LuDollarSign,
  [Icons.Download]: LuDownload,
  [Icons.Edit]: LuPencil,
  [Icons.Ellipsis]: LuEllipsis,
  [Icons.EllipsisVertical]: LuEllipsisVertical,
  [Icons.Email]: LuMail,
  [Icons.Export]: LuDownload,
  [Icons.Family]: LuUsers,
  [Icons.FAQ]: LuMessageCircle,
  [Icons.File]: LuFile,
  [Icons.Filter]: LuFilter,
  [Icons.Google]: FcGoogle,
  [Icons.Graduated]: LuGraduationCap,
  [Icons.Grid]: LuLayoutGrid,
  [Icons.Grip]: LuGrip,
  [Icons.Guides]: LuBookOpen,
  [Icons.Help]: LuCircleHelp,
  [Icons.History]: LuHistory,
  [Icons.Home]: LuHouse,
  [Icons.Import]: LuDownload,
  [Icons.Infinity]: LuInfinity,
  [Icons.Info]: LuInfo,
  [Icons.JSON]: BsFiletypeJson,
  [Icons.JSONSimple]: LuFileJson,
  [Icons.Light]: LuSun,
  [Icons.Link]: LuLink,
  [Icons.List]: LuMenu,
  [Icons.Logout]: LuLogOut,
  [Icons.Maximize]: LuMaximize2,
  [Icons.Minus]: LuMinus,
  [Icons.News]: LuNewspaper,
  [Icons.Notification]: LuBell,
  [Icons.Organization]: LuBuilding,
  [Icons.Party]: LuPartyPopper,
  [Icons.Pause]: LuPause,
  [Icons.PDF]: BsFiletypePdf,
  [Icons.PDFSimple]: LuChartColumn,
  [Icons.Play]: LuPlay,
  [Icons.Plus]: LuPlus,
  [Icons.Print]: LuPrinter,
  [Icons.QuestionMark]: LuCircleHelp,
  [Icons.Redo]: LuRedo,
  [Icons.Refresh]: LuRefreshCcw,
  [Icons.Report]: HiOutlineDocumentReport,
  [Icons.Save]: LuSave,
  [Icons.Session]: LuCalendarCheck,
  [Icons.Settings]: LuSettings,
  [Icons.Shield]: LuShield,
  [Icons.SortAlphabetical]: LuArrowDownAZ,
  [Icons.SortAlphabeticalReverse]: LuArrowUpZA,
  [Icons.Table]: LuTable,
  [Icons.Target]: LuTarget,
  [Icons.Timer]: LuTimer,
  [Icons.TimerReset]: LuTimerReset,
  [Icons.TrendingUp]: LuTrendingUp,
  [Icons.Unlink]: LuUnlink,
  [Icons.Upload]: LuUpload,
  [Icons.X]: LuX,
};
