import { HiOutlineDocumentReport } from 'react-icons/hi';
import {
  LuArrowLeft,
  LuBuilding,
  LuCalendarCheck,
  LuChartColumn,
  LuChartLine,
  LuCheck,
  LuCode,
  LuDollarSign,
  LuDownload,
  LuFileSpreadsheet,
  LuHistory,
  LuHouse,
  LuMoon,
  LuNewspaper,
  LuRefreshCcw,
  LuShield,
  LuSun,
  LuTrendingUp,
  LuUsers,
  LuX,
} from 'react-icons/lu';
import { RiParentLine } from 'react-icons/ri';

export enum Icons {
  ArrowLeft = 'ArrowLeft',
  Caregiver = 'Caregiver',
  Check = 'Check',
  Code = 'Code',
  CSVSimple = 'CSVSimple',
  Dark = 'Dark',
  Data = 'Data',
  DollarSign = 'DollarSign',
  Export = 'Export',
  Family = 'Family',
  History = 'History',
  Home = 'Home',
  Light = 'Light',
  News = 'News',
  Organization = 'Organization',
  PDFSimple = 'PDFSimple',
  Refresh = 'Refresh',
  Report = 'Report',
  Session = 'Session',
  Shield = 'Shield',
  TrendingUp = 'TrendingUp',
  X = 'X',
}

export const ICONS = {
  [Icons.ArrowLeft]: LuArrowLeft,
  [Icons.Caregiver]: RiParentLine,
  [Icons.Check]: LuCheck,
  [Icons.Code]: LuCode,
  [Icons.CSVSimple]: LuFileSpreadsheet,
  [Icons.Dark]: LuMoon,
  [Icons.Data]: LuChartLine,
  [Icons.DollarSign]: LuDollarSign,
  [Icons.Export]: LuDownload,
  [Icons.Family]: LuUsers,
  [Icons.History]: LuHistory,
  [Icons.Home]: LuHouse,
  [Icons.Light]: LuSun,
  [Icons.News]: LuNewspaper,
  [Icons.Organization]: LuBuilding,
  [Icons.PDFSimple]: LuChartColumn,
  [Icons.Refresh]: LuRefreshCcw,
  [Icons.Report]: HiOutlineDocumentReport,
  [Icons.Session]: LuCalendarCheck,
  [Icons.Shield]: LuShield,
  [Icons.TrendingUp]: LuTrendingUp,
  [Icons.X]: LuX,
};
